#!/bin/bash

# Detect if it's a 1st time installation

# Recommended by debian policy manual
set -e

# Print a greeting message on a 1st time installation

# Here the script is called with the configure argument
# but not provided with a version like so:
# postinst configure
# For upgrades, reconfigures, and everything else its:
# postinst configure 1.2-1

if [ "${1}" == "configure" ] && [ -z "${2}" ]
then
  echo ""
  echo "################################"
  echo "# Dehydrated Hook Script for Luadns.com"
  echo "################################"
  echo ""
  echo "  To Use, simply add the following to your dehydrated config:"
  echo "  CHALLENGETYPE=\"dns-01\""
  echo "  HOOK=\"/usr/bin/dehydrated-hook-luadns\""
  echo "  HOOK_CHAIN=\"no\""
  echo "  export lua_email=\"email@example.com\""
  echo "  export lua_api_key=\"123...abc...xyz\""
  echo "  export automatic_nginx_reload=\"yes\""
  echo ""
  echo "  Where lua_email is your Luadns.com login email and"
  echo "  lua_api_key is an api key generated via their WebUI."
  echo ""
  echo "  automatic_nginx_reload is optional if one is running"
  echo "  nginx as their webserver and wants to automatically"
  echo "  reload the config if a new certificate is issued."
  echo ""
  exit 0
else
  exit 0
fi


